version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    volumes:
      - .:/var/www/api.abz.igvend.com/laravel
    networks:
      - laravel
    platform: linux/amd64

  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/api.abz.igvend.com/laravel
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    platform: linux/amd64

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: abz
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
    platform: linux/amd64

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
